name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 4.2.2
  EXPORT_NAME: falling-blocks
  PROJECT_PATH: ./

jobs:
  # Determine the version number for this workflow.
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Get version number from tag
        id: tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> "${GITHUB_OUTPUT}"
    outputs:
      # Use the input from workflow dispatch, or fall back to the git tag.
      version: ${{ inputs.version || steps.tag.outputs.tag }}
  export-web:
    needs:
      - get-version
    env:
      VERSION: ${{ needs.get-version.outputs.version }}
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p /tmp/build/web
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "HTML5" /tmp/build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: /tmp/build/web
      - name: Install curl
        run: sudo apt install libcurl4-openssl-dev
      - name: Install butler
        run: |
          curl -L -o butler.zip 'https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default'
          unzip butler.zip
          chmod +x butler
          ./butler -V
      - name: Upload all packages to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
        run: |
          # for channel in $(ls tmp); do
            ./butler push \
              --fix-permissions \
              --userversion='${{ env.VERSION }}' \
              tmp/build/web/* \
              '${{ env.EXPORT_NAME }}':"web"
          # done
